//! Trilateral build seat selector.
//!
//! The Asolaria OS is ONE shared source with ONE shared driver set. Each federation machine
//! (acer / liris / relic, and later any auto-provisioned node) gets its OWN kernel that is
//! device-specific, PID-specific, and fabric-specific. Relic is OP-FELIPE's computer;
//! OP-FELIPE is a human operator, not a machine or seat. Only the *seat label* is a build-time
//! parameter here — the device identity itself is NOT baked in: the kernel mints `device_pid`
//! at boot from the live read-only PCI inventory + RTC/TSC (see `boot/src/hwinv.rs`).
//!
//! Usage (the trilateral GitHub build runs this three times):
//!   ASOLARIA_SEAT=acer  cargo build --release --target x86_64-unknown-uefi --bin asolaria-os
//!   ASOLARIA_SEAT=liris cargo build ...
//!   ASOLARIA_SEAT=relic cargo build ...
//! Unset defaults to `liris` (this clone's seat).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=ASOLARIA_SEAT");

    let seat = env::var("ASOLARIA_SEAT").unwrap_or_else(|_| "liris".to_string());
    let seat = seat.trim().to_string();

    // The seat label is copied into fixed 256/448-byte boot row buffers (hwinv/driver) via
    // put_bytes, and embedded in a serial marker the CI gate greps. Keep it small + ascii-safe.
    assert!(!seat.is_empty(), "ASOLARIA_SEAT must not be empty");
    assert!(
        seat.len() <= 32,
        "ASOLARIA_SEAT too long (max 32 bytes): {seat:?}"
    );
    assert!(
        seat.bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-'),
        "ASOLARIA_SEAT must match [a-z0-9-]+: {seat:?}"
    );

    // The human/pixel projection row. The hardware-derived BOOTPID/BOOTTIME/BOOTPROJ rows remain
    // the machine-readable authority; this row only states the build-time seat boundary.
    let row = format!(
        "ASOBTID|format=hbpish|evidence=BUILD_TIME_SEAT_CONTEXT|source=uefi|seat={seat}|device_identity=runtime-pci-60d|boot_identity=runtime-rtc-tsc|authority=unsealed|e=0|fire=0|json=0"
    );

    let generated = format!(
        "// @generated by kernel/boot/build.rs from ASOLARIA_SEAT — do not edit by hand.\n\
         /// Build-seat label for this machine-specific kernel artifact (trilateral build).\n\
         const BOOT_SEAT: &[u8] = b\"{seat}\";\n\
         /// Human/pixel projection of the build-seat boundary (seat baked in at build time).\n\
         const BOOT_SEAT_ROW: &[u8] = b\"{row}\";\n"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out_dir).join("seat_config.rs");
    fs::write(&dest, generated).expect("write seat_config.rs");
}
