//! Trilateral build seat selector.
//!
//! The Asolaria OS is ONE shared source with ONE shared driver set. Each federation machine
//! (acer / liris / relic, and later any auto-provisioned node) gets its OWN kernel that is
//! device-specific, PID-specific, and fabric-specific. Relic is OP-FELIPE's computer;
//! OP-FELIPE is a human operator, not a machine or seat. Only the *seat label* is a build-time
//! parameter here — the device identity itself is NOT baked in: the kernel mints `device_pid`
//! at boot from the live read-only PCI inventory + RTC/TSC (see `boot/src/hwinv.rs`).
//!
//! Usage (the trilateral GitHub build runs this three times):
//!   ASOLARIA_SEAT=acer  cargo build --release --target x86_64-unknown-uefi --bin asolaria-os
//!   ASOLARIA_SEAT=liris cargo build ...
//!   ASOLARIA_SEAT=relic cargo build ...
//! Unset defaults to `liris` (this clone's seat).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=ASOLARIA_SEAT");
    println!("cargo:rerun-if-env-changed=ASOLARIA_BOOT_MODE");

    let seat = env::var("ASOLARIA_SEAT").unwrap_or_else(|_| "liris".to_string());
    let seat = seat.trim().to_string();

    // Boot mode: "kernel" (default — current behavior, diverges into init::run() and becomes the
    // OS) or "pre-windows" (finite local-disk stage: emit the identity rows, then return
    // EFI_NOT_FOUND so the firmware boot manager continues to the next BootOrder entry, i.e.
    // Windows). OP-JESSE canon: Asolaria boots from the local internal drive BEFORE Windows, then
    // hands back. The USB is never the staging target.
    let boot_mode = env::var("ASOLARIA_BOOT_MODE").unwrap_or_else(|_| "kernel".to_string());
    let boot_mode = boot_mode.trim().to_string();
    assert!(
        matches!(boot_mode.as_str(), "kernel" | "pre-windows"),
        "ASOLARIA_BOOT_MODE must be kernel or pre-windows: {boot_mode:?}"
    );
    let pre_windows_handoff = boot_mode == "pre-windows";

    // The seat label is copied into fixed 256/448-byte boot row buffers (hwinv/driver) via
    // put_bytes, and embedded in a serial marker the CI gate greps. Keep it small + ascii-safe.
    assert!(!seat.is_empty(), "ASOLARIA_SEAT must not be empty");
    assert!(
        seat.len() <= 32,
        "ASOLARIA_SEAT too long (max 32 bytes): {seat:?}"
    );
    assert!(
        seat.bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-'),
        "ASOLARIA_SEAT must match [a-z0-9-]+: {seat:?}"
    );

    // The human/pixel projection row. The hardware-derived BOOTPID/BOOTTIME/BOOTPROJ rows remain
    // the machine-readable authority; this row only states the build-time seat boundary.
    let row = format!(
        "ASOBTID|format=hbpish|evidence=BUILD_TIME_SEAT_CONTEXT|source=uefi|seat={seat}|device_identity=runtime-pci-60d|boot_identity=runtime-rtc-tsc|authority=unsealed|e=0|fire=0|json=0"
    );

    // handoff_return=true means the pre-windows stage returns to firmware (EFI_NOT_FOUND); the
    // successor is firmware-defined (not necessarily Windows), and Asolaria is not resident.
    let boot_mode_row = format!(
        "ASOBTMODE|format=hbpish|evidence=BUILD_TIME_BOOT_MODE|source=uefi|seat={seat}|mode={boot_mode}|handoff_return={pre_windows_handoff}|next=firmware-defined|resident_supervision=0|authority=operator-configured|e=0|fire=0|json=0"
    );

    let generated = format!(
        "// @generated by kernel/boot/build.rs from ASOLARIA_SEAT/ASOLARIA_BOOT_MODE — do not edit by hand.\n\
         /// Build-seat label for this machine-specific kernel artifact (trilateral build).\n\
         const BOOT_SEAT: &[u8] = b\"{seat}\";\n\
         /// Human/pixel projection of the build-seat boundary (seat baked in at build time).\n\
         const BOOT_SEAT_ROW: &[u8] = b\"{row}\";\n\
         /// True only for the finite local-disk stage that runs before Windows and returns to firmware.\n\
         const BOOT_PRE_WINDOWS_HANDOFF: bool = {pre_windows_handoff};\n\
         /// HBP-ish declaration of the selected boot mode.\n\
         const BOOT_MODE_ROW: &[u8] = b\"{boot_mode_row}\";\n"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out_dir).join("seat_config.rs");
    fs::write(&dest, generated).expect("write seat_config.rs");
}
