//! Build-time codegen of atlas tables from C:/HyperBEHCS/store/atlas-canonical-1024.hbp.
//! AR3 Proposal B per asolaria-metal layer 68 atlas_rework.
//!
//! This script parses the HBP pipe-delim atlas and emits Rust match arms into
//! OUT_DIR/atlas_generated.rs which the kernel can include via include!().
//! Until validated, the kernel still uses hand-coded match arms in src/atlas/mod.rs;
//! the generated file is canonical-fallback / drift-check only.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let hbp_path = "C:/HyperBEHCS/store/atlas-canonical-1024.hbp";
    println!("cargo:rerun-if-changed={}", hbp_path);

    let Ok(content) = fs::read_to_string(hbp_path) else {
        println!("cargo:warning=atlas-canonical-1024.hbp not found; skipping codegen");
        return;
    };

    let mut rows = Vec::new();
    for line in content.lines() {
        if !line.starts_with("HATLASCP|") {
            continue;
        }
        let mut cp: u16 = 0;
        let mut domain = String::new();
        let mut supervisor = String::new();
        let mut lane = String::new();
        for part in line.split('|') {
            let Some(eq) = part.find('=') else {
                continue;
            };
            let key = &part[..eq];
            let val = &part[eq + 1..];
            match key {
                "cp" => cp = val.parse().unwrap_or(0),
                "domain" => domain = val.to_string(),
                "supervisor" => supervisor = val.to_string(),
                "lane" => lane = val.to_string(),
                _ => {}
            }
        }
        rows.push((cp, domain, supervisor, lane));
    }

    let mut out = String::from(
        "// AUTO-GENERATED by build.rs from atlas-canonical-1024.hbp; do not edit by hand.\n\n",
    );
    out.push_str(&format!(
        "pub const ATLAS_CP_COUNT_FROM_HBP: u16 = {};\n\n",
        rows.len()
    ));

    // Emit domain-for-cp match arms (matches kernel atlas/mod.rs hand-coded table)
    out.push_str("pub const fn domain_for_cp_generated(cp: u16) -> Option<&'static str> {\n");
    out.push_str("    match cp {\n");
    for &(cp, ref domain, ref _sup, ref _lane) in &rows {
        out.push_str(&format!("        {} => Some(\"{}\"),\n", cp, domain));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Same for supervisor + lane
    out.push_str("pub const fn supervisor_for_cp_generated(cp: u16) -> Option<&'static str> {\n    match cp {\n");
    for &(cp, ref _domain, ref sup, ref _lane) in &rows {
        out.push_str(&format!("        {} => Some(\"{}\"),\n", cp, sup));
    }
    out.push_str("        _ => None,\n    }\n}\n\n");

    out.push_str(
        "pub const fn lane_for_cp_generated(cp: u16) -> Option<&'static str> {\n    match cp {\n",
    );
    for &(cp, ref _d, ref _s, ref lane) in &rows {
        out.push_str(&format!("        {} => Some(\"{}\"),\n", cp, lane));
    }
    out.push_str("        _ => None,\n    }\n}\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("atlas_generated.rs"), out).expect("write atlas_generated.rs");
}
